#include "PeepholeOptimizer.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

namespace {

string trim(string s)
{
    while (!s.empty() && isspace(static_cast<unsigned char>(s.front())))
        s.erase(s.begin());

    while (!s.empty() && isspace(static_cast<unsigned char>(s.back())))
        s.pop_back();

    return s;
}

string lowerCopy(string s)
{
    transform(s.begin(), s.end(), s.begin(), [](unsigned char c) {
        return static_cast<char>(tolower(c));
    });
    return s;
}

bool isCommentOrBlank(const string& line)
{
    string t = trim(line);
    return t.empty() || t[0] == ';';
}

bool isLabel(const string& line, string& label)
{
    string t = trim(line);
    if (t.size() >= 2 && t.back() == ':')
    {
        label = trim(t.substr(0, t.size() - 1));
        return !label.empty();
    }
    return false;
}

bool parseTwoOperand(
    const string& line,
    string& op,
    string& first,
    string& second)
{
    string t = trim(line);
    if (t.empty() || t[0] == ';')
        return false;

    size_t space = t.find_first_of(" \t");
    if (space == string::npos)
        return false;

    op = lowerCopy(trim(t.substr(0, space)));
    string rest = trim(t.substr(space + 1));

    size_t comma = rest.find(',');
    if (comma == string::npos)
        return false;

    first = lowerCopy(trim(rest.substr(0, comma)));
    second = lowerCopy(trim(rest.substr(comma + 1)));
    return true;
}

bool parseOneOperand(const string& line, string& op, string& operand)
{
    string t = trim(line);
    if (t.empty() || t[0] == ';')
        return false;

    size_t space = t.find_first_of(" \t");
    if (space == string::npos)
        return false;

    op = lowerCopy(trim(t.substr(0, space)));
    operand = lowerCopy(trim(t.substr(space + 1)));
    return !operand.empty();
}

string replaceJumpTarget(
    const string& line,
    const unordered_map<string, string>& redirect)
{
    string t = trim(line);
    if (t.empty() || t[0] == ';')
        return line;

    size_t space = t.find_first_of(" \t");
    if (space == string::npos)
        return line;

    string op = lowerCopy(trim(t.substr(0, space)));
    string target = trim(t.substr(space + 1));

    // Only rewrite direct branch targets. These are the branches generated by
    // the Phase-1 visitor.
    static const vector<string> jumps = {
        "jmp", "je", "jne", "jl", "jle", "jg", "jge", "jz", "jnz"
    };

    if (find(jumps.begin(), jumps.end(), op) == jumps.end())
        return line;

    auto it = redirect.find(target);
    if (it == redirect.end())
        return line;

    string indentation = line.substr(0, line.find_first_not_of(" \t"));
    return indentation + op + " " + it->second;
}

vector<string> removeRedundantLabels(const vector<string>& lines)
{
    unordered_map<string, string> redirect;
    vector<bool> remove(lines.size(), false);

    string canonical;
    bool inLabelRun = false;

    for (size_t i = 0; i < lines.size(); ++i)
    {
        string label;
        if (isLabel(lines[i], label))
        {
            if (!inLabelRun)
            {
                canonical = label;
                inLabelRun = true;
            }
            else
            {
                redirect[label] = canonical;
                remove[i] = true;
            }
        }
        else if (!isCommentOrBlank(lines[i]))
        {
            inLabelRun = false;
            canonical.clear();
        }
    }

    vector<string> result;
    for (size_t i = 0; i < lines.size(); ++i)
    {
        if (!remove[i])
            result.push_back(replaceJumpTarget(lines[i], redirect));
    }

    return result;
}

vector<string> removeSimpleRedundancy(const vector<string>& lines)
{
    vector<string> result;

    for (size_t i = 0; i < lines.size(); ++i)
    {
        string op, a, b;

        // MOV X, X
        if (parseTwoOperand(lines[i], op, a, b) &&
            op == "mov" && a == b)
        {
            continue;
        }

        // ADD/SUB X, 0 and IMUL X, 1
        if (parseTwoOperand(lines[i], op, a, b))
        {
            if ((op == "add" || op == "sub") && b == "0")
                continue;

            if (op == "imul" && b == "1")
                continue;
        }

        // Adjacent PUSH X / POP X
        if (i + 1 < lines.size())
        {
            string op1, x;
            string op2, y;

            if (parseOneOperand(lines[i], op1, x) &&
                parseOneOperand(lines[i + 1], op2, y) &&
                op1 == "push" && op2 == "pop" && x == y)
            {
                ++i;
                continue;
            }
        }

        // MOV A, B followed immediately by MOV B, A -> second MOV is redundant.
        if (!result.empty())
        {
            string pOp, pA, pB;
            if (parseTwoOperand(result.back(), pOp, pA, pB) &&
                parseTwoOperand(lines[i], op, a, b) &&
                pOp == "mov" && op == "mov" &&
                pA == b && pB == a)
            {
                continue;
            }
        }

        result.push_back(lines[i]);
    }

    return result;
}

} // namespace

void PeepholeOptimizer::optimize(
    const string& inputFile,
    const string& outputFile)
{
    ifstream in(inputFile);
    if (!in)
        throw runtime_error("Could not open " + inputFile);

    vector<string> lines;
    string line;
    while (getline(in, line))
        lines.push_back(line);

    // A couple of small passes are enough because removing one instruction can
    // expose a new adjacent peephole opportunity.
    vector<string> optimized = removeRedundantLabels(lines);
    optimized = removeSimpleRedundancy(optimized);
    optimized = removeSimpleRedundancy(optimized);

    ofstream out(outputFile, ios::trunc);
    if (!out)
        throw runtime_error("Could not create " + outputFile);

    for (const string& current : optimized)
        out << current << '\n';
}
